### ISSUE TITLE
Starting vim-swoop from Visual mode

### ISSUE THREAD

**Issue by balta2ar** [pelodelfuego/vim-swoop#19]
In current implementation if vim-swoop starts from Visual mode, currently selected word (or many words) are treated as a pattern.

I suggest to add another feature: if we are in Visual mode and we have many lines selected, starting vim-swoop will limit its range to only those lines. This might be useful if I want to proceed with some refactoring only within a single function: I select that function, start vim-swoop, type pattern and replace variable name as required.

**Comment by pelodelfuego** [comment]
I already thought about this feature but after a while, i realized that it was not on the swoop dogme.

When you use swoop as a refactoring tool, it is for entire (or multiple) files. If you need to refactor only a few lines, you should use a tool like [multiple cursor](https://github.com/terryma/vim-multiple-cursors) or [vim-asterisk](https://github.com/haya14busa/vim-asterisk).

On top of that how would behave multi buffer mode ? What do you think about that ?

**Comment by balta2ar** [comment]
Huh, this is funny. There was a post on one site where in comments I offered vim-multiple-cursor plugin to the author as a refactoring tool. Later someone replied to my comment and showed me vim-swoop, that's how I found you. Now you're suggesting me vim-multiple-cursors back again :)

Thanks, I use these plugins all the time, they are indeed great. And you're right, I didn't think about multi buffer mode. I can't offer any reasonable behavior at the moment.

**Comment by pelodelfuego** [comment]
Actually, I think the idea behind vim-swoop is refactoring for whole (or multiple) files like function renaming. The abaility to see the context allow a global view of what you're doing.

To rename for example a variable, a tool like multiple cursor is better because you work on a local context.

You should give a try to vim-asterisk, combined with ```nmap § .n``` it allow refactoring in multiple cursor style but staying consitent with vim philosophy.
I recently began to work on a fork (see keepcursor feature) which allow you to refactor with a few keystroke (like multiple cursors does)
