### ISSUE TITLE
Possible multiple instances (on multiple tabs) support?

### ISSUE THREAD

**Issue by xdxter** [pelodelfuego/vim-swoop#30]
Not sure if by design, but I can't seem to open multiple Swoop instances across different tabs.

Steps to repro:
1. Open a swoop instance using :Swoop
2. Goto a new tab using :tabnew FILE2
3. Attempt to open another Swoop instance in the new tab using :Swoop

Step 3 doesn't work, it seemingly just removes the 1st line in the current buffer in the new tab.

**Comment by pelodelfuego** [comment]
Yes, 
The swoop buffer may enter in conflict if multiple instances of swoop are running. 
We would need to create multiple buffers according to current tab but I'm not sure about the variables visibility between tabs, any clue about it? 
Would you like to submit a pull request?

**Comment by xdxter** [comment]
Thanks for the quick reply!

I have minimal experience in VimL, so unfortunately I wouldn't volunteer to solve this. But I'd love to see this issue fixed!! :P

**Comment by pelodelfuego** [comment]
Hi xdxter ! 

I've been checking how complicated will be adding this feature and it turns out it will be lot of work.

Maybe for a major update or port to neovim it could worst it. 
The ratio time spent / added value of this functionality is quite low in my opinion but I may have missed something? 

Could you detail the usecase you need multiple swoop sessions opened at the same time? 

Cheers!
