### ISSUE TITLE
Compatibility with ihacklog/HiCursorWords

### ISSUE THREAD

**Issue by iglesias** [pelodelfuego/vim-swoop#37]
![Alt Text](https://media.giphy.com/media/xUA7b8d2Fyo6zSTpQY/giphy.gif)

Is this a known issue with some solution or workaround? Thanks!

**Comment by pelodelfuego** [comment]
Hi !

Issue is not known, I'll dig into it next week I think,
Ty for feedback!

**Comment by pelodelfuego** [comment]
Sorry for my late, late catch up.

No the issue is not known but most likely fall on the bucket:
"Having 2 plugins manipulating cursor position at the same time get things messy"

A solution could be to use the `freezeContext` function provided but then all the interest of this other plugin is lost.

I'm not sure there are any easy fix here since it includes prioritizing event triggers,
Would you have any idea about an acceptable workaround ?

**Comment by iglesias** [comment]
Sadly not, I don't have any. Shall we keep the issue open? It would be great if someone can come up with a fix.

**Comment by pelodelfuego** [comment]
Hum,

Yes I think we should keep this open, maybe someone will pop out with an awesome idea =)

Thank you very much for raising the problem anw.
