### ISSUE TITLE
Multiple `undo` eventually results in the Swoop buffer being cleared

### ISSUE THREAD

**Issue by jeetsukumaran** [pelodelfuego/vim-swoop#8]
If the user hits ``u`` sufficient times, the Swoop buffer gets cleared or restored to a previous non-relevant state. Not sure how to fix this except by intercepting `u` (and its variants) and not letting it proceed beyond the point, or if there is a flag to use when programmatically setting up the swoop buffers that skip population of the changelist.

**Comment by pelodelfuego** [comment]
I see what you mean but no idea about how achieve it.
I'm documenting, let me know if you find a solution...

**Comment by jeetsukumaran** [comment]
Yes, I think this is going to be tough. Is there a way to make programmatic changes to a buffer and avoid it being added to the changelist? I do not know. Maybe you can ask on the vim-dev list or stack overflow? Alternatively, as I said, map the `u` etc. keys to a special ``SwoopUndo()`` function which only allows undo's back to the a particular point, i.e., right after the Swoop buffer was created.

**Comment by pelodelfuego** [comment]
I'm looking at undojoin, 
Maybe a good start

**Comment by pelodelfuego** [comment]
Issue should now be solved.
Can you confirm me you can't reproduce this issue anymore ?

**Comment by jeetsukumaran** [comment]
Hmmm. Is this on master? I still can undo to the point of swoop-buffer 
creation. I can undo even without making edits to the buffer, e.g., 
going to previous strings I have searched for in the same session.

On 1/13/15 6:37 PM, pelodelfuego wrote:
> Issue should now be solved.
> Can you confirm me you can't reproduce this issue anymore ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelodelfuego/vim-swoop/issues/8#issuecomment-69843677>.
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by pelodelfuego** [comment]
Yes, it is on master, it juste seems the issue still to solve =(

**Comment by pelodelfuego** [comment]
Unfortunalty yes =(
But the issue seems fixed on my configuration.

Could you give me a minimal example ?
Are you sure you have no swoopBuf saved on your drive ?

**Comment by pelodelfuego** [comment]
Pushed a small modif on dev branch,  (ie ```bwipeout``` instead of ```bdelete```)
That may solve the issue ?

**Comment by pelodelfuego** [comment]
I think i just understood the issue you are describing:
Since the beginning i thought you were talking about this issue in 2 different swoop session but actually you are talking about the same session, correct ?

About the unrelavant state, it is actually the "step" before reaching the final pattern (ie leaving insert mode). For exemple:

If you want to search "let":
1/ you type "l"
1.5/ buffer update "l" pattern
2/ you type "e"
2.5/ buffer update "le" pattern
3/ you type "t"
4.5/ buffer update "let" pattern

To Vim's point of view, only one action on the pattern, but 3 on the buffer.

Due to autoCommand in Insert mode (each keypress launch ```s:cursorMoved()```) and the vim's undo mecanism for undo (undo granularity is toogling mode), the issue is not really an unrelavant state but rather an highlight problem.

What do you think about this perspective ?

**Comment by jeetsukumaran** [comment]
Try this:

(1) Open a swoop on a set of files, and type in ``l``,``e``,``t``, as above
(2) Hit ``<ESC>``
(3) Type ``u`` 6 times

The first three times, sure: you are reversing the search input. Ideally, after that we get lots of other results that are ghosts of past searches.

Ideally, the ``undo`` command should *only* be applied to edits on the swoop buffer by the user, not even on programmatic changes to the swoop buffer that the swoop plugin makes in response to the user modifying the search string.

**Comment by pelodelfuego** [comment]
Managed to visualize the undo sequence:
(comment line ```autocmd!    BufLeave   swoopBuf   :call SwoopSaveAndQuit()``` and use UndoTree)

The problem is that i can't make : ```undojoin | ProgramaticFunction``` work properly, it seems to have no effect... Do you have any idea about it or how to use undojoin correctly ?

**Comment by jeetsukumaran** [comment]
I'm afraid not. As I mentioned, the strategy that occurs to me would be to record the index of the undo tree at the point the Swoop buffer is programmatically created or updated. Then special SwoopUndo/SwoopRedo functions (to which 'u', 'r', etc. are mapped within the swoop buffer) will work to undo/redo user edits, but not let the user jump back in the undo tree beyond that starting index. You can look at undotree or gundo for ideas on how to work with the undo tree.

**Comment by pelodelfuego** [comment]
Just push a solution on dev:
I split undoblocks at each insert on a pattern, that hide unrelevant states but you need to many times to get a good result so i'm not satisfied. I think the old behaviour is better, what is your feelings ?

However, implement an undo/redo mecanism is too complicated for the actual benefit. Indeed, since loosing focus on swoopBuf exit and save, you can't use a tool like undoTree or Gundo.

Moreover, the undo / redo mecanism must not disturb the editing on line for refactoring (the main purpose of this plugin).

I begin to think that Vim is just not design yet to tweak its undoTree...

Anyway, keep me in touch when you try it and we'll take a decision durng the next week.

**Comment by pelodelfuego** [comment]
I choosed to keep it the old way, not optimal but can't find a proper solution (and god know i've searched =p ).

If someone have a precise idea about how to get undojoin working with programatic entries, let me know.
